const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
    user_role: {type: String, default: null},
    plan: {type: String, default: null},
    first_name : {type: String, default: null},
    middle_name : {type: String, default: null},
    last_name : {type: String, default: null},
    email: {type: String, default: null},
    password:{type: String},
    mobile: {type: String, default: null},
    company_name:{type: String, default: null},
    company_type:{type: String, default: null},
    cin:{type: String, default: null},
    msme:{type: Boolean, default: false},
    pan:{type: String, default: null},
    gst: {type: String, default: null},
    c_address1:{type: String, default: null},
    c_address2:{type: String, default: null},
    c_landmark:{type: String, default: null},
    c_city:{type: String, default: null},
    c_state:{type: String, default: null},
    b_address1:{type: String, default: null},
    b_address2:{type: String, default: null},
    b_landmark:{type: String, default: null},
    b_city:{type: String, default: null},
    b_state:{type: String, default: null},
    company_category:{type: String, default: null},
    annual_sales:{type: String, default: null},
    website: {type: String, default: null},
    instagram: {type: String, default: null},
    facebook:{type: String, default: null},
    employee_no:{type: String, default: null},
    company_across_india:{type: Boolean, default: false},
    family_name : {type: String, default: null},
    name : {type: String, default: null},
    token:{type: String},
    logo: {type: String}
    // {
    //     data: Buffer,
    //     contentType: String
    // }

    // phone_no:{type: String},
    // address_1: {type: String},
    // address_2: {type: String},
    // landmark: {type: String},
    // country: {type: String},
    // state: {type: String},
    // city: {type: String},
    // pincode: {type: String},
    // account_holder: {type: String},
    // account_number: {type: String},
    // account_type: {type: String},
    // bank_name: {type: String},
    // ifsc_code: {type: String},
    // branch_name: {type: String},
    // bank_address: {type: String},
    // company_website: {type: String},
    // company_size: {type: String},
    // about: {type: String},
    // research_method: {type: String},
    // available_language: {type: String},
    // research_location: {type: String},
    // maximum_distance: {type: String},
    // quota_per_day: {type: Number},
})

module.exports = mongoose.model("user", userSchema);